### PR TITLE
Split libadios2 (C++) from adios2 (Python)

### LINKED ISSUE #54: Split into C++ library and Python packages
It would be helpful if the ADIOS2 package was split in to a (1) C++ library package and a (2) Python package. The issue is that packages that depend on the ADIOS2 C++ interface/library but not on Python get a transitive dependency on Python. See, for example, https://github.com/conda-forge/fenics-dolfinx-feedstock/issues/15.

### PR DESCRIPTION
**Pull request by minrk**
Mostly achieved by splitting only the install step via components.

- `libadios2` is a new package, and contains only the C++ libraries
- `adios2` is unchanged, and adds the Python dependency and components
- Achieved via patch that marks Python components (`adios2_python-python` and `adios2_scripts-runtime`) with EXCLUDE_FROM_ALL so that they don't get installed by default
- Install script and env for libadios is unchanged, only _what is installed_
- `adios2` install script runs the additional component installs to get back to the original full install.

If I knew a way to explicitly say "install all but components X, Y" I would, but I haven't found a way to do that with cmake.

The bit I don't love is that the Python dependencies are duplicated:

- they are in libadios because they are actually needed for the build. Then they are _excluded_ via `ignore_run_exports_from`
- they are in adios2 but actually unused during install, because that's where the run_exports (from Python and numpy) are actually needed

closes #54 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by minrk** [comment]
Lint on pin_compatible is incorrect: https://github.com/conda-forge/conda-smithy/pull/1642

**Comment by minrk** [comment]
@conda-forge-admin please rerender

**Comment by ax3l** [comment]
@chuckatkins can you comment on this need of the conda-forge maintainers?

**Comment by minrk** [comment]
This is truly wild - all builds passed yesterday except some ppc timeouts, and after a one character change today, zfp isn't found and now ffs is missing??

**Comment by minrk** [comment]
@ax3l I _think_ this is finally going to pass. Apparently both cmake 3.24 and zfp 1.0 are out since yesterday, and both _separately_ cause the build to fail.

zfp 1.0 fails with https://github.com/ornladios/ADIOS2/issues/3303

cmake 3.24 with:

```
CMake Error at CMakeLists.txt:9 (find_package):
  Found package configuration file:

    $PREFIX/lib/cmake/adios2/adios2-config.cmake

  but it set adios2_FOUND to FALSE so package "adios2" is considered to be
  NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing: ffs::ffs
```

Ideally, when there's one C++ library and multiple Python bindings, it's nice to build the C++ lib once and link to it from the Python wrappers, each packaged separately. This way downstream packages like `fenics-libdolfinx` that only depend on the C library don't pull in Python as a transitive dependency (and thereby a potentially large build matrix).

This is tricky when it's all in one CMake project, but splitting only the install step is one approach that's simplest from a cmake perspective. The downside is it complicates meta.yaml by requiring Python dependencies to be specified twice.

Another option would be to try to separate the actual _build_ to try to build the Python bindings in a separate step. This would probably make `meta.yaml` more straightforward, but at the cost of complicating the build _itself_ since it's not meant to work that way (and I don't actually know how to get started trying to do it).

**Review by ax3l — APPROVED** [review]
This looks good to me, I'd merge this in but I might need to reach out in the future if I get lost in the conda logic.

**Comment by minrk** [comment]
Thanks! Always feel free to ping me.

**Comment by ax3l** [comment]
Thanks a lot :)

**Comment by ax3l** [comment]
Hi @minrk, it looks like all the new migration PRs fail. Can you help? I cannot figure out whats wrong in the deps.

**Comment by minrk** [comment]
Yes, I will look at those today. Sorry for the trouble!

**Pull request merged**
