### PR TITLE
[Patch] ChunkV Offset Fix

### PR DESCRIPTION
**Pull request by ax3l**
Fix compressor issue, first seen with C-Blosc2:
Fix ChunkV maintaining CurOffset when downsizing current chunk in Allocate() and creating the next chunk.

Ref.: https://github.com/ornladios/ADIOS2/pull/3769

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Review by vicentebolea — APPROVED** [review]

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
(c-blosc 2.10.2 is out now :) )

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
