### PR TITLE
Enable PyPy (All Artifacts)

### PR DESCRIPTION
**Pull request by ax3l**
I did forget some builds in #66.
- [ ] depends on https://github.com/ornladios/ADIOS2/issues/2068

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
@minrk do I need to exclude some Python tests for some of the artifacts? Or is this an upstream issue?

**Comment by minrk** [comment]
Judging by the `ModuleNotFoundError: No module named 'adios2.adios2'` error, I think the adios2 shared library target filename is not correct. It's producing the tag `.pypy39-pp73.so` when other packages are producing `.pypy39-pp73-x86_64-linux-gnu.so` (it's missing the platform part of the tag). So it's not found at import time.

I'm not sure how the target filename is picked by CMake, but standard Python build mechanisms should retrieve the right name.

**Comment by ax3l** [comment]
Thank you for the pointer! :)

I think the logic resides here:
- https://github.com/ornladios/ADIOS2/blob/v2.8.3/bindings/Python/CMakeLists.txt

Ususally the pybind11 `pybind11_extension` helper function is used to set the right `SUFFIX` in CMake projects.

I think ADIOS2 uses `PYTHON_ADD_LIBRARY` from:
- https://github.com/ornladios/ADIOS2/blob/v2.8.3/cmake/upstream/FindPython.cmake
- https://github.com/ornladios/ADIOS2/blob/v2.8.3/cmake/upstream/FindPython/Support.cmake#L3129-L3143

**Comment by vicentebolea** [comment]
@conda-forge-admin, please rerender

**Comment by vicentebolea** [comment]
@ax3l is this still good to have?

**Comment by ax3l** [comment]
Yes, I think that would be good to support.

**Review by vicentebolea — APPROVED** [review]

**Pull request merged**
