### PR TITLE
OSX: Enable Extensions

### PR DESCRIPTION
**Pull request by ax3l**
Try to enable extensions and fix the OSX toolchain.

to do:
- [x] do we have to set `CMAKE_SYSTEM_PROCESSOR` for `dill`? -> toolchain reduced
- [x] if we set it to `$ENV{OSX_ARCH}`, [basically it's `x86_64`](https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html#environment-variables-set-during-the-build-process), how to fix the toolchain issue? -> toolchain reduced

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
@williamfgc @chuckatkins you probably can answer the question in the PR description. On OSX, what is expected to be set in CMake so `dill` recognizes the processor properly? I just placed `amd64` in there (via `$ENV{OSX_ARCH}`) but this then causes other problems when finding dependencies.

**Comment by williamfgc** [comment]
@axl3 I am not familiar with the dill dependency. @eisenhauer can you help @ax3l ? Thanks!

**Comment by ax3l** [comment]
ping @eisenhauer can we take a look at this? I am also living closer to your timezone now, so VCs are possible anytime ;)

**Comment by eisenhauer** [comment]
At least one useful thing to know here is what CMAKE_SYSTEM_PROCESSOR is actually set to.  If it's set to something that is just another alias for the set of things that dill already recognizes for x86, then life is easy.  If it's unset, or set to something generic, then we need somewhat different logic.

**Comment by chuckatkins** [comment]
> On OSX, what is expected to be set in CMake so `dill` recognizes the processor properly?
> 
> ```
> ...
> -- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
> -- Could NOT find LibFFI (missing: LIBFFI_LIBRARIES) 
> -- Disabling emulation
> CMake Error at thirdparty/dill/dill/CMakeLists.txt:254 (message):
>   Configure has detected no native dynamic code generation support
> 
>      for this architecture ("UNSUPPORTED"), -DDILL_MULTI_TARGET=ON 
>      was not specified, and no emulation is possible (libffi library 
>      not found)
>      NO LIBRARY WILL BE BUILT

You shouldn't have to set anything.  The CMake code is using the value of `uname -p` which on OSX is going to be `i386` and should be recognized by dill.

@KyleFromKitware, can you see if this is somehow a specific interaction to a different environment when building within anaconda on OSX?

**Comment by ax3l** [comment]
If I do not set it in my toolchain file, `CMAKE_SYSTEM_PROCESSOR` is empty from what I checked. Therefore, `dill` goes to `unknown` processor.

**Comment by KyleFromKitware** [comment]
@ax3l Please post a copy of your toolchain file We may need to adjust it.

**Comment by chuckatkins** [comment]
> If I do not set it in my toolchain file, `CMAKE_SYSTEM_PROCESSOR` is empty from what I checked. Therefore, `dill` goes to `unknown` processor.

I expect this has to do with the toolchain files putting things in cross-compiling mode.  I think the toolchain files are overkill and likely problematic.  Try just putting the bare essentials in the toolchain file:
```
set(CMAKE_SYSTEM_PREFIX_PATH $ENV{BUILD_PREFIX}/$ENV{HOST}/sysroot)
set(CMAKE_FIND_ROOT_PATH $ENV{PREFIX} $ENV{BUILD_PREFIX}/$ENV{HOST}/sysroot)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```

And let the host detection stuff do the work it needs to do.

**Comment by ax3l** [comment]
will push a commit to try this. the osx toolchain file seams to be use for all CMake projects conda-forge wide.

@KyleFromKitware the toolchain file is in the PR, it's called `recipe/cross-osx.cmake` :)

**Comment by ax3l** [comment]
If I remember @mingwandroid correctly, performing these builds in cross-compile mode is intentional.

**Comment by ax3l** [comment]
Huh, works!

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by chuckatkins** [comment]
There's a lot of of system interrogation that happens when building in host mode that missing in cross compilation mode and needs to be explicitly setup.  If you don't have a need for cross compilation then it's best to avoid.

**Comment by ax3l** [comment]
Sounds good to me, thanks a lot!

**Pull request merged**
