### PR TITLE
Enable PyPy

### PR DESCRIPTION
**Pull request by ax3l**
See: https://github.com/ornladios/ADIOS2/issues/2068

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
With the latest pybind11 updates in ADIOS2 v2.7.0 this might actually work now...

**Comment by ax3l** [comment]
Ah, besides the update, ADIOS2 does not yet use the new `FindPython.cmake` module I think... That might be needed here.

**Comment by chuckatkins** [comment]
> Ah, besides the update, ADIOS2 does not yet use the new `FindPython.cmake` module I think... That might be needed here.

It should.  If using CMake < 3.18 adios is using it's internal copy but if using CMake >= 3.18 it just uses cmake's version.

**Comment by ax3l** [comment]
Oh, in that case we might need to update the `-DPYTHON_EXECUTABLE` hint to `-DPython_EXECUTABLE`

**Comment by ax3l** [comment]
Hm, the module name `adios2.pypy36-pp73.so` looks a bit wrong. It lacks the platform suffix, e.g. `adios2.pypy36-pp73-linux-gnu.so`.

**Comment by williamfgc** [comment]
https://github.com/conda-forge/adios2-feedstock/blob/master/recipe/meta.yaml#L41 should be honored?

**Comment by ax3l** [comment]
No, that's just the conda package name.

I think the problem is somewhere here:
https://github.com/ornladios/ADIOS2/blob/v2.7.0/bindings/Python/CMakeLists.txt#L12

Instead, those helpers can be used:
https://github.com/openPMD/openPMD-api/blob/0.13.1/CMakeLists.txt#L557-L558

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
Well, #25 solves it :D

**Comment by ax3l** [comment]
Will continue tracking this until upstream ADIOS2 fixes it (https://github.com/ornladios/ADIOS2/issues/2068) via #66 at Conda-Forge

**Pull request closed without merging**
